version: '3.8'

services:
  backend_main:
    build:
      context: .
      dockerfile: docker/Dockerfile_back
    container_name: backend-container
    env_file: docker/.env
    networks:
      - receipt-network

  frontend:
    build:
        context: .
        dockerfile: docker/Dockerfile_front
    restart: unless-stopped
    env_file: docker/.env
    ports:
      - "8000:80"
    depends_on:
      - backend_main
    networks:
      - receipt-network

networks:
  receipt-network:
