"""“add_cooking_type_to_the_receipt”

Revision ID: 1366e0dc77cb
Revises: 4112d77a5895
Create Date: 2023-11-25 20:11:00.199706

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1366e0dc77cb'
down_revision: Union[str, None] = '4112d77a5895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt', sa.Column('cooking_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'receipt', 'cooking_type', ['cooking_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'receipt', type_='foreignkey')
    op.drop_column('receipt', 'cooking_type_id')
    # ### end Alembic commands ###
