"""fix unit fk in component

Revision ID: 316c486c5975
Revises: 225fbb3ba271
Create Date: 2023-11-12 18:10:50.468744

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '316c486c5975'
down_revision: Union[str, None] = '225fbb3ba271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt_component', sa.Column('unit_id', sa.Integer(), nullable=True))
    op.drop_constraint('receipt_component_unit_fkey', 'receipt_component', type_='foreignkey')
    op.create_foreign_key(None, 'receipt_component', 'measure_unit', ['unit_id'], ['id'])
    op.drop_column('receipt_component', 'unit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt_component', sa.Column('unit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'receipt_component', type_='foreignkey')
    op.create_foreign_key('receipt_component_unit_fkey', 'receipt_component', 'measure_unit', ['unit'], ['id'])
    op.drop_column('receipt_component', 'unit_id')
    # ### end Alembic commands ###
