"""“measure_unit_symbol_is_unique”

Revision ID: 4112d77a5895
Revises: 316c486c5975
Create Date: 2023-11-25 19:35:57.035204

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4112d77a5895'
down_revision: Union[str, None] = '316c486c5975'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredient', 'product_link')
    op.drop_index('ix_measure_unit_symbol', table_name='measure_unit')
    op.create_index(op.f('ix_measure_unit_symbol'), 'measure_unit', ['symbol'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_measure_unit_symbol'), table_name='measure_unit')
    op.create_index('ix_measure_unit_symbol', 'measure_unit', ['symbol'], unique=False)
    op.add_column('ingredient', sa.Column('product_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
