"""“add_catetory_type”

Revision ID: 481d0b029114
Revises: 1366e0dc77cb
Create Date: 2023-11-26 15:35:32.014541

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '481d0b029114'
down_revision: Union[str, None] = '1366e0dc77cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'culinary_category',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_culinary_category_id'), 'culinary_category', ['id'], unique=False)
    op.add_column('receipt', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'receipt', 'culinary_category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'receipt', type_='foreignkey')
    op.drop_column('receipt', 'category_id')
    op.drop_index(op.f('ix_culinary_category_id'), table_name='culinary_category')
    op.drop_table('culinary_category')
    # ### end Alembic commands ###
