"""“include_component_type_receipt”

Revision ID: 8ed11a5d58ba
Revises: 481d0b029114
Create Date: 2023-11-26 16:30:32.735617

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8ed11a5d58ba'
down_revision: Union[str, None] = '481d0b029114'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt_component', sa.Column('component_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'receipt_component', 'receipt_component_type', ['component_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'receipt_component', type_='foreignkey')
    op.drop_column('receipt_component', 'component_type_id')
    # ### end Alembic commands ###
