"""create receipt and directory models

Revision ID: cee0f686fe33
Revises: fc4c4eacff53
Create Date: 2023-11-12 16:40:17.665798

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cee0f686fe33'
down_revision: Union[str, None] = 'fc4c4eacff53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'cooking_type',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cooking_type_id'), 'cooking_type', ['id'], unique=False)
    op.create_table(
        'ingredient',
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('product_url', sa.String(), nullable=True),
        sa.Column('product_link', sa.String(), nullable=True),
        sa.Column('product_data', sa.JSON(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredient_description'), 'ingredient', ['description'], unique=False)
    op.create_index(op.f('ix_ingredient_id'), 'ingredient', ['id'], unique=False)
    op.create_table(
        'measure_unit',
        sa.Column('symbol', sa.String(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measure_unit_id'), 'measure_unit', ['id'], unique=False)
    op.create_index(op.f('ix_measure_unit_symbol'), 'measure_unit', ['symbol'], unique=False)
    op.create_table(
        'receipt_component_type',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_component_type_id'), 'receipt_component_type', ['id'], unique=False)
    op.create_table(
        'receipt',
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('procedure', sa.String(), nullable=True),
        sa.Column('source_link', sa.String(), nullable=True),
        sa.Column('author_id', sa.Integer(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_description'), 'receipt', ['description'], unique=False)
    op.create_index(op.f('ix_receipt_id'), 'receipt', ['id'], unique=False)
    op.create_index(op.f('ix_receipt_name'), 'receipt', ['name'], unique=False)
    op.create_table(
        'receipt_component',
        sa.Column('amount', sa.Float(), nullable=True),
        sa.Column('unit', sa.Integer(), nullable=True),
        sa.Column('receipt_id', sa.Integer(), nullable=True),
        sa.Column('ingredient_id', sa.Integer(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
        sa.ForeignKeyConstraint(['receipt_id'], ['receipt.id'], ),
        sa.ForeignKeyConstraint(['unit'], ['measure_unit.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_component_id'), 'receipt_component', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipt_component_id'), table_name='receipt_component')
    op.drop_table('receipt_component')
    op.drop_index(op.f('ix_receipt_name'), table_name='receipt')
    op.drop_index(op.f('ix_receipt_id'), table_name='receipt')
    op.drop_index(op.f('ix_receipt_description'), table_name='receipt')
    op.drop_table('receipt')
    op.drop_index(op.f('ix_receipt_component_type_id'), table_name='receipt_component_type')
    op.drop_table('receipt_component_type')
    op.drop_index(op.f('ix_measure_unit_symbol'), table_name='measure_unit')
    op.drop_index(op.f('ix_measure_unit_id'), table_name='measure_unit')
    op.drop_table('measure_unit')
    op.drop_index(op.f('ix_ingredient_id'), table_name='ingredient')
    op.drop_index(op.f('ix_ingredient_description'), table_name='ingredient')
    op.drop_table('ingredient')
    op.drop_index(op.f('ix_cooking_type_id'), table_name='cooking_type')
    op.drop_table('cooking_type')
    # ### end Alembic commands ###
