"""init migration

Revision ID: fc4c4eacff53
Revises:
Create Date: 2023-08-27 18:49:19.103488

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fc4c4eacff53'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('password', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('user_type', sa.Enum('CLIENT', 'ADMIN', 'MODERATOR', name='usertypeenum'), nullable=True),
        sa.Column('has_api_access', sa.Boolean(), nullable=True),
        sa.Column('telegram_id', sa.Integer(), nullable=True),
        sa.Column('first_name', sa.String(length=35), nullable=True),
        sa.Column('last_name', sa.String(length=35), nullable=True),
        sa.Column('full_name', sa.String(length=35), nullable=True),
        sa.Column('name', sa.String(length=35), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.execute('DROP TYPE usertypeenum')
    # ### end Alembic commands ###
