FROM node:latest as build-stage
WORKDIR /app
COPY frontend/package*.json ./
RUN npm install
COPY frontend/ .
ENV VUE_APP_BACKEND_SERVER_URL=http://localhost:5000
RUN npm run build

FROM nginx as production-stage
RUN mkdir /app
COPY --from=build-stage /app/dist /app
COPY docker/nginx.conf /etc/nginx/nginx.conf
#RUN rm -f  /etc/nginx/conf.d/default.conf
#COPY docker/nginx.conf /etc/nginx/conf.d/receipt.conf
#RUN  sed -i "s/127.0.0.1:5000/backend_main:5000/g" /etc/nginx/conf.d/receipt.conf
